# Generated by Django 5.2.3 on 2025-07-04 11:55

import django.core.validators
from django.db import migrations, models

import apps.core.upload_paths
import apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture (optional).",
                null=True,
                upload_to=apps.core.upload_paths.user_avatar_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif"]
                    ),
                    apps.core.validators.validate_image_size,
                ],
                verbose_name="Avatar",
            ),
        ),
    ]
