# Generated by Django 5.2.3 on 2025-07-03 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_published_post_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publish_date',
        ),
    ]
