# Generated by Django 5.2.3 on 2025-07-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_publish_post_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='published_at',
        ),
    ]
