# Generated by Django 5.2.3 on 2025-07-03 15:35

import apps.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_publish_date_post_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.blog.models.post_image_upload_path),
        ),
    ]
