# Generated by Django 5.2.3 on 2025-07-04 11:57

import apps.core.upload_paths
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_alter_post_image_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.upload_paths.post_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), apps.core.validators.validate_image_size]),
        ),
    ]
