# Generated by Django 5.2.3 on 2025-07-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_is_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_spam',
        ),
    ]
