# Generated by Django 5.2.3 on 2025-07-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_post_is_spam'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, default='0.0.0.0', null=True),
        ),
    ]
