# Generated by Django 5.2.3 on 2025-07-03 15:35

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography (optional).', null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (optional).', null=True, upload_to=apps.users.models.user_avatar_upload_path, verbose_name='Avatar'),
        ),
    ]
